#!/bin/bash
# launches mpv with a unique mpv socket at /tmp/mpvsockets
# https://github.com/seanbreckenridge/mpv-sockets

socket_dir='/tmp/mpvsockets'
mpv_path="${MPV_PATH:-/usr/bin/mpv}"
readonly mpv_path socket_dir

[[ ! -e "${mpv_path}" ]] && {
	printf 'Error: could not find mpv at "%s"\nSet the MPV_PATH environment variable to the absolute path of mpv\n' "${mpv_path}" >&2
	exit 1
}

# make sockets directory
mkdir -p "${socket_dir}" || exit $?

# exec mpv, with the --input-ipc-server flag, using epoch nanoseconds
# to guarantee unique ipc sockets
declare -a mpv_options
mpv_options=(--input-ipc-server="${socket_dir}/$(date +%s%N)")
mpv_options+=("$@")

exec "${mpv_path}" "${mpv_options[@]}"
