#!/bin/bash -u
# interactively pick one of the active mpv instances,
# and send it a 'quit' command

abort() {
	echo "$1" 1>&2
	exit 1
}

declare -a active
declare chosen

if active=($(mpv-active-sockets)); then
	chosen=$({
		for socket in "${active[@]}"; do
			printf "%s:" "$socket"
			mpv-get-property "$socket" 'path' || exit $?
		done
	} | fzf +m -i --prompt="Select mpv instance to quit > ") || abort "No instance selected..."
	if [[ -n "${chosen}" ]]; then
		exec mpv-communicate "${chosen%%:*}" 'quit'
	else
		abort "Error getting selected instance..."
	fi
else
	abort "No active mpv instances..."
fi
