#!/usr/bin/env bash
# interactively pick one of the active mpv instances
# print the socket file path

set -e

abort() {
	echo "$1" >&2
	exit 1
}

declare -a active
declare chosen

# shellcheck disable=SC2207
if active=($(mpv-active-sockets)); then
	chosen="$({
		for socket in "${active[@]}"; do
			printf '%s:' "${socket}"
			mpv-get-property "${socket}" 'path' || exit $?
		done
	} | fzf +m -i --prompt='Select mpv instance... > ')" || abort 'No instance selected...'
	if [[ -n "${chosen}" ]]; then
		echo "${chosen%%:*}"
	else
		abort 'Error getting selected instance...'
	fi
else
	abort 'No active mpv instances...'
fi
