#!/bin/bash -u
# interactively pick one of the active mpv instances,
# and send it a 'quit' command

declare chosen

if chosen="$(mpv-pick)"; then
	exec mpv-communicate "${chosen}" 'quit'
else
	exit 1
fi
