#!/usr/bin/env python3
# same as mpv-song-description, uses python to speedup the string/json manipulation
# is faster to do this in python,
# otherwise need to do lots of jq/string manipulation
# is about 25-30% faster

import os
import sys
import json
import subprocess

os.environ["MPV_DESC_RAW"] = "1"

proc = subprocess.run("mpv-song-description", stdout=subprocess.PIPE)
if proc.returncode != 0:
    sys.exit(proc.returncode)

print_album = "MPV_DESC_SKIP_ALBUM" not in os.environ

data = json.loads(proc.stdout.decode("utf-8"))

title = data.get("title", "").replace(os.linesep, "").strip()
artist = data.get("artist", "").replace(os.linesep, "").strip()
album = ""

desc = ""
if print_album:
    album = data.get("album", "").replace(os.linesep, "").strip()

if title:
    desc = title
if artist:
    if desc:
        desc = f"{desc} - {artist}"
    else:
        desc = artist

if album:
    desc = f"{desc} ({album})"

print(desc)
