#!/usr/bin/env bash
# go to the next song in the playlist for the currently playing mpv instance

IFS=$'\n'
declare -a playing

# shellcheck disable=SC2207
if playing=($(mpv-currently-playing --socket)); then
	exec mpv-communicate "${playing[-1]}" '{ "command": ["playlist-next"] }'
else
	echo 'No mpv instances which are currently playing media...' >&2
	exit 1
fi
